# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44c6d4149ebd00eb5251da13b21e7ee0c397d188c40e44d8b6189d8b2b871afbf1519707e844497ad179b6c107220d56563befca6a5e512ed80e13b3034d7df3

test:
  secret_key_base: 58207f37e4c9d7542765ee860c6d0bf39f9af380ebb947b127739f8e6397feffe67d146818255df08a9457a8d85a291969ab9d85f3b08d94a5265bd7e3d1fb78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
